
[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DiffResults = "163ba53b-c6d8-5494-b064-1a9d43ac40c5"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LazyArrays = "5078a376-72f3-5289-bfd5-ec5146d43c02"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
CairoMakie = "~0.15.2"
DiffResults = "~1.1.0"
FillArrays = "~1.13.0"
ForwardDiff = "~1.0.1"
LazyArrays = "~2.6.1"
RecursiveArrayTools = "~3.33.0"
Rotations = "~1.7.1"

