
[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecursiveArrayTools = "731186ca-8d62-57ce-b412-fbd966d074cd"
SizeCheck = "e0176837-3861-45f9-8fb4-a12fc39b9661"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
AbstractGPs = "~0.5.24"
CSV = "~0.10.15"
CairoMakie = "~0.15.6"
DataFrames = "~1.8.1"
DataFramesMeta = "~0.15.5"
Distributions = "~0.25.122"
KernelFunctions = "~0.10.66"
LogExpFunctions = "~0.3.29"
PDMats = "~0.11.36"
PythonCall = "~0.9.28"
RecursiveArrayTools = "~3.39.0"
SizeCheck = "~0.1.0"
SpecialFunctions = "~2.6.1"
StatsBase = "~0.34.7"

